### ISSUE TITLE
Bug al crear puerta sobre ventana

### ISSUE THREAD

**Issue by alvaromw** [voidpixel/tickets#11]
No se si esta reportado pero por si acaso. Si pones una puerta encima de la ventana, ¿debería recalcular la ventana? o quizás debería no dejarte poner la puerta. A parte que no recalcula el pathfinding y no deja entrar por la puerta, entiendo que es por que la ventana esta en medio y no calcula el hueco.

![image](https://github.com/voidpixel/tickets/assets/5238152/945c452d-4724-4d5c-9d51-4552bb166f6a)

**Comment by pagoru** [comment]
Va de la mano con https://github.com/voidpixel/tickets/issues/4, lo marcare como duplicado porque voy a arreglar todo en la misma tarea https://github.com/voidpixel/tasks/issues/219.
Que basicamente no se puedan poner objetos, paredes, puertas o ventanas en el mismo sitio
