### ISSUE TITLE
El ratón funciona estando en la Tablet

### ISSUE THREAD

**Issue by alvaromw** [voidpixel/tickets#12]
El ratón sigue interactuando con la escena cuando estas dentro de la interfaz de la Tablet. En la imagen no se ve el ratón pero esta situado donde la pared de abajo y la hace desaparecer.

![image](https://github.com/voidpixel/tickets/assets/5238152/bde4b39f-b0c9-4223-977a-e76bc92df23c)

**Comment by pagoru** [comment]
- build-2 https://github.com/voidpixel/tasks/issues/237
