### ISSUE TITLE
Pantalla negra cuando elimino un furni en la tablet

### ISSUE THREAD

**Issue by ovniroto** [voidpixel/tickets#14]
Me ha pasado ya varias veces que intentando crear una letra con bloques a diferentes alturas y demás en la tablet, después de girar el furni para intentar ver qué estoy creando, si pulso el botón de la papelera para eliminarlo se pone todo negro y tengo que volver a iniciar el juego. 

No puedo reproducir los pasos porque intento hacerlo a posta y no pasa, pero me ha sucedido varias veces intentando crear algo y luego eliminando el furni habiendo girado para ver las diferentes caras.

**Comment by pagoru** [comment]
Voy a trabajar en esta posible solución, aun sabiendo que es 100% culpa de PIXI. build-2 https://github.com/voidpixel/tasks/issues/254

+contexto https://discord.com/channels/734147990985375826/1182437250324246538
