### ISSUE TITLE
Mi experiencia creando furnis

### ISSUE THREAD

**Issue by ovniroto** [voidpixel/tickets#15]
Entiendo que es la primera versión, pero supongo que todo cuenta para mejorar la experiencia de usuario a futuro.

La experiencia que he tenido al crear cosas con el creador de furnis actual es bastante desastrosa, no por los controles, sino porque no sé exactamente dónde estoy poniendo los bloques. Al crear algo en un entorno "3D", necesitas si o si saber dónde estás poniendo cada cosa, y yo al menos me he sentido muy perdido en este aspecto.

Sigo creyendo que un [sistema como el de picocad](https://img.itch.zone/aW1hZ2UvODg0NjIzLzUyNTM1MDAuZ2lm/347x500/Hi5LnO.gif) sería mucho más fácil de gestionar para todo el mundo, no solo porque puedes controlar cada lado, sino porque estaría bien poder seleccionar "capas" y moverlas en diferentes direcciones o ampliarlas, etc, en vez de solo ir con un pixel y estirarlo. El modo de creación actual puede llegar a ser bastante lento y tosco para alguien que quiera dedicarse a crear objetos.

**Comment by pagoru** [comment]
Toda la razón del mundo. Me planteare de nuevo esta idea, ya que la actual ha fallado estrepitosamente. Aunque se tenia que probar la idea, por eso al final es la v0. Thanks por el feedback sincero! :D 

build-2 https://github.com/voidpixel/tasks/issues/255
