### ISSUE TITLE
Estar haciendo una foto no debería esconder paredes.

### ISSUE THREAD

**Issue by mcmacker4** [voidpixel/tickets#16]
Durante gameplay normal, las paredes desaparecen y aparecen al pasar el ratón por encima.
Es una buena funcionalidad.

El problema viene cuando estamos haciendo una foto con la PDA. Las paredes aparecen y desaparecen mientras estamos intentando hacer una foto. Pienso que deberían estar fijas mientras hacemos la foto.

**Comment by pagoru** [comment]
build-2 https://github.com/voidpixel/tasks/issues/237
