### ISSUE TITLE
Los furnis se quedan invisibles en el centro del mapa aunque los lleves a la caja

### ISSUE THREAD

**Issue by ovniroto** [voidpixel/tickets#17]
Trasteando un poco con los furnis he visto que al llevarlos a la caja con click derecho, se acumulan en el centro del mapa pero invisibles, o algo por el estilo, y no deja pasar al personaje o se queda encajado dentro del furni invisible sin que se pueda mover. Dejo estos vídeos de muestra.

https://github.com/voidpixel/tickets/assets/2887878/b65c3f37-3089-46b2-ae93-2d4ca32d3875

https://github.com/voidpixel/tickets/assets/2887878/7c41664f-e826-4116-97a7-0351189d92c7

**Comment by pagoru** [comment]
El problema es que, aunque no te fijes, estás moviendo la pantalla ligeramente cuando hacer click (seguramente tengas la sensibilidad del ratón muy alta o con mucha precision) y eso hace que el target del personaje no se active. Tengo que mejorar esto, pero no tiene nada que ver con los objetos.
- build-2 https://github.com/voidpixel/tasks/issues/233

**Comment by ovniroto** [comment]
Creo que no es por el click, pasa igualmente si lo hago lento o doy varios clicks. En este video se puede ver que justo en el centro hay algo invisible y de un punto a otro no pasa por el centro sino que da la vuelta.
https://github.com/voidpixel/tickets/assets/2887878/8e47b8ce-65bb-44f4-a33a-359d0384300c

**Comment by pagoru** [comment]
![image](https://github.com/voidpixel/tickets/assets/1551265/3538c32a-b82e-43a8-9c09-6e250af39953)
mmm, hay algun bug recalculando el pathfinding, pero creo que no necesariamente tiene que ser el centro.
Investigaré... pero si, hay un bug. Pensé que era porque hacias click muy rapido, pero nanai 
build-2 https://github.com/voidpixel/tasks/issues/257
