### ISSUE TITLE
Al cerrar y abrir el juego cambian los objetos

### ISSUE THREAD

**Issue by alqubo** [voidpixel/tickets#18]
En la app Cad v0 , he creado un macetero (obj 1), sobre ese le he puesto un cactus (obj 2), y sobre él le he puesto una base roja (obj 3).

Los 3 estaban puestos en el mundo de forma aleatoria, y se renderizaban correctamente, pero al cerrar y abrir el juego se han convertido todos a obj 3

![image](https://github.com/voidpixel/tickets/assets/9885515/2b8305a4-0cd7-4e7e-8d96-8a3a93d2d347)

**Comment by alqubo** [comment]
He realizado otra prueba y pasa exactamente igual
![image](https://github.com/voidpixel/tickets/assets/9885515/f124e86b-4b4b-4aaa-9996-b713d6005e88)

Al cerrar y abrir

![image](https://github.com/voidpixel/tickets/assets/9885515/660b90ca-e8cb-44c2-b662-08305d02028a)

**Comment by pagoru** [comment]
![voidpixel_zE5zG5AQLj](https://github.com/voidpixel/tickets/assets/1551265/73d9188a-d96c-4cc5-8f87-838e72b0541a)
![voidpixel_idGgjQGFfO](https://github.com/voidpixel/tickets/assets/1551265/bf094d63-cd02-42f7-b184-09f449ceaed0)

Yeeep... build-2 https://github.com/voidpixel/tasks/issues/256
