### ISSUE TITLE
Ocultar paredes afecta al movimiento del personaje

### ISSUE THREAD

**Issue by alqubo** [voidpixel/tickets#19]
Si mientras el personaje se esta moviendo pasas el cursor sobre paredes, parece que el personaje intente ir hacia atrás y luego continuar.

https://discord.com/channels/224590605559398410/1187543936215040050/1187543936215040050

**Comment by pagoru** [comment]
Que mac estás usando? Modelo, año y demás? He hecho la misma prueba en mac y sin problemas 🤔 
<img width="1439" alt="image" src="https://github.com/voidpixel/tickets/assets/1551265/a97f58bc-74a7-45ea-824f-3949623f225e">

**Comment by alqubo** [comment]
@pagoru 
![image](https://github.com/voidpixel/tickets/assets/9885515/60e9b8f4-e54e-4af5-9f07-67369b45673b)

**Comment by alqubo** [comment]
Si, en la última disponible

**Comment by pagoru** [comment]
@alqubo El comportamiento de las paredes ha cambiado completamente, sigue ocurriendo en la build-2?

**Comment by alqubo** [comment]
> @alqubo El comportamiento de las paredes ha cambiado completamente, sigue ocurriendo en la build-2?

Parece que no consigo reproducirlo @pagoru
