### ISSUE TITLE
Discord presence not working

### ISSUE THREAD

**Issue by alqubo** [voidpixel/tickets#2]
![image](https://github.com/voidpixel/tickets/assets/9885515/a0ff2949-9b38-4203-8688-c8e181785835)
![image](https://github.com/voidpixel/tickets/assets/9885515/07e5ff7e-de6e-4f65-9798-1a6fecf64893)

En MAC no reconoce el juego de primeras, pero si lo metes manualmente desde ajustes de discord tampoco aparece el logo de la demo

**Comment by pagoru** [comment]
duplicated #1
