### ISSUE TITLE
Objetos de la caja aparecen en el mundo

### ISSUE THREAD

**Issue by alqubo** [voidpixel/tickets#20]
Al cerrar y abrir el juego de nuevo, los objetos de la caja aparecen en el mundo, en lugar de en la caja

![image](https://github.com/voidpixel/tickets/assets/9885515/a85fcaa9-130e-498c-8f44-8bb8ca56bb2b)

**Comment by pagoru** [comment]
No consigo reproducir el bug... :( 

Te recomiendo empezar con una partida limpia y volver a probar, si sigue ocurriendo, lo miro con más detalle.
Recuerda borrar la carpeta:
```
windows: %appdata%/voidpixel/db
mac: Library/Application Support/voidpixel/db
linux: $XDG_CONFIG_HOME or ~/.config/voidpixel/db
```
