### ISSUE TITLE
Bug al mover el ratón y al hacer clic

### ISSUE THREAD

**Issue by ovniroto** [voidpixel/tickets#21]
Al mover el ratón da saltos todo el rato y al hacer click en alguna posición todo el juego se para, si te fijas hasta la fogata para de animarse.

https://www.youtube.com/watch?v=axH-vNA0D10

Specs donde lo he probado:
- i7-2600K
- 16 gb ram
- nvidia gtx 960
- win 11

**Comment by pagoru** [comment]
Sobre el click, es el tema del pathfinding, que no va a ser solucionado en la demo, pero lo tengo en cuenta para la siguiente versión. Es el tema del loop de darker-engine, así que no problema.

Sobre lo de los saltos del ratón, tengo que investigar, por que hay momentos que lo he visto, pero no consigo reproducirlo más veces como tu. 
Te recomiendo por si las moscas desactivar el F3

**Comment by ovniroto** [comment]
Me pasa con y sin F3, lo activé por si te servía de algo la info que da.

**Comment by pagoru** [comment]
Si puedes probar este ejemplo https://mdn.github.io/dom-examples/pointer-lock/ y decirme si te funciona bien o tambien te da saltos?

**Comment by pagoru** [comment]
Creo que he encontrado el problema.
![image](https://github.com/voidpixel/tickets/assets/1551265/04e34aa5-4fae-4907-9549-1e57c877d36c)
He añadido una opción nueva en los settings, que va a venir marcada por defecto, pero la puedes desmarcar.
