### ISSUE TITLE
Las paredes no se ocultan cuando intentas construir suelo

### ISSUE THREAD

**Issue by cout970** [voidpixel/tickets#3]
Cuando no tienes nada seleccionado en la mano, se ocultan las paredes debajo del cursor, pero al colocar suelo o muebles no funciona igual.

Si construyes paredes para hacer una casa y después intentas colocar el suelo o un mueble, no puedes seleccionar bien las esquinas porque quedan ocultas tras las paredes.

**Comment by pagoru** [comment]
Task created on https://github.com/voidpixel/tasks/issues/218
