### ISSUE TITLE
Los muebles pueden atravesar paredes

### ISSUE THREAD

**Issue by cout970** [voidpixel/tickets#4]
Hice una alfombra y me deja colocarla dentro de la pared, queda bastante raro, se podria limitar la posición o hacer que se vea correctamente atravesando la esquina.

![image](https://github.com/voidpixel/tickets/assets/4961713/a12f4533-b428-4b25-a4ae-0488688ee130)

**Comment by pagoru** [comment]
I'm gonna fix this for the build-2 https://github.com/voidpixel/tasks/issues/219

**Comment by pagoru** [comment]
Not anymore! 👯
