### ISSUE TITLE
Interacciones con la tablet

### ISSUE THREAD

**Issue by cout970** [voidpixel/tickets#6]
Esto es más una mejora que un bug, pero se me hace muy raro que el cursor sobre la tablet tenga icono de "mano" para interacturar y sobre los botones iconos de "cursor" normal de no interactuar.

También se me hace raro que no tenga efecto hover, ni tooltip para explicar que hace el boton.

En la App de CAD intento colocar cubos haciendo click y arrastrando, pero haciendo eso se mueve la tablet. Tienes que hacer click, soltar, moverte y hacer click de nuevo, creo que sería más natura hacer click y sin soltar mover hasta el final y soltar click.

Cuando intentas crear un cubo grande en la app de CAD, si mueves el raton fuera del área valida donde colocar cubos, ignora la posicion del raton y no actualiza el cubo, tienes acercar el raton a dentro del área para que actualice. Para aclarar, muevo el raton desde donde empieza la flecha hasta donde termina, pero el cubo de la preview se queda a medio camino:
![image](https://github.com/voidpixel/tickets/assets/4961713/259974df-5237-47bb-9b74-a70e65463c46)

No va le CTRL + Z en la app de CAD, tampoco hay opción para desactivar la transparencia de los cubos colocados, se mezcla con el fondo y dificulta ver la altura del cubo con respecto del resto.

**Comment by pagoru** [comment]
All done!
