### ISSUE TITLE
La ventanas se ven mal cuando la pared está hacia la izquierda

### ISSUE THREAD

**Issue by cout970** [voidpixel/tickets#8]
Captura, bastante explicativa:
![image](https://github.com/voidpixel/tickets/assets/4961713/c1544625-adc5-4748-9907-a4ec89f198d8)

Tambien se ve mal la preview de ventana en este ángulo de pared

**Comment by pagoru** [comment]
La preview ya esta arreglada en la 1.1.1.
El bug en build-2 ya que es un poco más complicado y lo llevo arrastrando un tiempo https://github.com/voidpixel/tasks/issues/231
