### ISSUE TITLE
Al soltar un mueble, el click afecta también al mueble de atras

### ISSUE THREAD

**Issue by cout970** [voidpixel/tickets#9]
Si intentas colocar un mueble al lado de otro, cuando haces click para soltar el mueble nuevo, el click no solo colaca el mueble, tambien selecciona el mueble anterior, haciendo que tengas que colocarlo de nuevo en su lugar.

**Comment by pagoru** [comment]
fixing this on build-2 https://github.com/voidpixel/tasks/issues/232
